---
title: "Modelo predictivo de desnutrición aguda a partir de factores medioambientales"
author: "Luis Revilla"
date: "2022-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data geoespacial

Utilizando Google Cloud CLI y el paquete de R llamado "rgee" para utilizar Google Earth Engine se obtuvo la data del año 2019, por meses, de la precipitación y la temperatura del Perú.

```{r Google Earth Engine}
library(raster)
library(terra)
library(ggplot2)

precipitation <- rast("rasters/pp_2019.tif")
temp_max <- rast("rasters/temp_max_2019.tif")
temp_min <- rast("rasters/temp_min_2019.tif")
```

## Precipitación


```{r precipitation, echo=FALSE}

plot(precipitation, main="Precipitation IDAHO Terraclimate - Peru 2019", xlab="Longitude", ylab="Latitude")


```

## Temperatura Máxima

```{r temp_max, echo=FALSE}
plot(temp_max, main="Maximum temperature IDAHO Terraclimate - Peru 2019", xlab="Longitude", ylab="Latitude", )
```

## Temperatura Mínima

```{r temp_min, echo=FALSE}
plot(temp_min, main="Minimum temperature IDAHO Terraclimate - Peru 2019", xlab="Longitude", ylab="Latitude", )
```


## Cálculo de desnutrición aguda
```{r}
library(tidyverse)
library(haven)
library(fs)
library(readr)
library(dplyr)

years <- c("2014", "2015", "2016", "2017", "2018", "2019")

for(i in 1:5) {
  doc_path <- path("dataset")
  year_path <- path(years[i])
  final_path <- path(doc_path, year_path)
  
  child_path <- "RECH6.SAV"
  house_path <- "RECH0.SAV"
  
  variable_child_path <- path(final_path, child_path)
  variable_house_path <- path(final_path, house_path)
  
  child <- read_sav(variable_child_path) %>%
    select(HHID, HC12, HC3, HC2, HC1, HC72) %>%
    filter(HC12 != 99998) %>%
    mutate(weight = HC2/10, height = HC3/10, age = HC1)
  
  child <- mutate(child, malnutrition = HC12/100) %>%
    mutate(malnutrition = case_when(
      malnutrition < 89 ~ 1,
      TRUE ~ 0)) 

  if (i == 2){
    house <- read_sav(variable_house_path) %>%
      select(HHID, LONGITUDX, LATITUDY, HV025, HV024) %>%
      mutate(longitudx = LONGITUDX, latitudy = LATITUDY) %>%
      select(-c(LONGITUDX, LATITUDY))
  }

  else if (i==4){
    house <- read_sav(variable_house_path) %>%
      select(HHID, long_ccpp, lat_ccpp, HV025, HV024) %>%
      mutate(longitudx = long_ccpp, latitudy = lat_ccpp) %>%
      select(-c(long_ccpp, lat_ccpp))
  }
        
  
  else{
    house <- read_sav(variable_house_path) %>%
      select(HHID, longitudx, latitudy, HV025, HV024)
  }
  df <- 
  child %>% 
  inner_join(house, by = "HHID") %>%
  mutate(area_residence =  HV025, region = HV024) %>%
  select(-c(HV025,HV024,HC12,HC3,HC1,HC2,HC72))
  
  malnutrition_path <- paste("malnutrition_",years[i],".csv", sep = "")
  dataset_path <- path(final_path, malnutrition_path)
  write_csv(df, dataset_path)   
}
  
# doc_path <- path("dataset/2018")
# child_path <- "RECH6.SAV"
# house_path <- "RECH0.SAV"
# 
# variable_child_path <- path(doc_path, child_path)
# variable_house_path <- path(doc_path, house_path)
# 
# child <- read_sav(variable_child_path)
# house <- read_sav(variable_house_path)
# 
# house <- house %>%
#   select(HHID, longitudx, latitudy, HV025, HV024)
# 
# child <- child %>%
#   select(HHID, HC12, HC3, HC2, HC1, HC72) %>%
#   filter(HC12 != 99998) %>%
#   mutate(weight = HC2/10, height = HC3/10, age = HC1)
# 
# child <- mutate(child, malnutrition = HC12/100) %>%
#   mutate(malnutrition = case_when(
#     malnutrition < 89 ~ 1,
#     TRUE ~ 0)) 
# 
# df <- 
#   child %>% 
#   inner_join(house, by = "HHID") %>%
#   mutate(area_residence =  HV025, region = HV024) %>%
#   select(-2,-3,-4,-5,-6,-13,-14)
# 
# write_csv(df, "D:/PUCP-UPCH/Innova Lab/Tesis/malnutrition_climate/dataset/malnutrition.csv")

```

```{r}
library(tidyverse)
library(haven)
library(fs)
library(readr)
library(dplyr)

path_2014 <- path("dataset/2014/malnutrition_2014.csv")
malnutrition_2014 <- read_csv(path_2014)

path_2015 <- path("dataset/2015/malnutrition_2015.csv")
malnutrition_2015 <- read_csv(path_2015)

path_2016 <- path("dataset/2016/malnutrition_2016.csv")
malnutrition_2016 <- read_csv(path_2016)

path_2017 <- path("dataset/2017/malnutrition_2017.csv")
malnutrition_2017 <- read_csv(path_2017)

path_2018 <- path("dataset/2018/malnutrition_2018.csv")
malnutrition_2018 <- read_csv(path_2018)

path_2019 <- path("dataset/2019/malnutrition_2019.csv")
malnutrition_2019 <- read_csv(path_2019)

```

